<?php

/**
 * @file
 * Hook implementations for the IBM video media type module.
 *
 * @todo Finish bundle for IBM video.
 * @todo Figure out what to do with field validation.
 * @todo Finish code review.
 * @todo Test.
 */

declare (strict_types = 1);

/**
 * Implements hook_theme().
 */
function ibm_video_media_type_theme($existing, $type, $theme, $path) {
  return [
    'ibm_video_media_type_player' => [
      'variables' => [
        'videoUrl' => '',
        '#attached' => ['library' => ['css/ibm_video_media_type_player']],
      ],
      'template' => 'templates/ibm_video_media_type_player',
    ],
  ];
}
