<?php

/**
 * @file
 * Hook implementations for the IBM video media type module.
 *
 * @todo Figure out how to handle local thumbnail URI storage (whether to fetch
 * each time, validation, etc.)
 * @todo Finish implementing thumbnail support.
 * @todo Review.
 * @todo Test.
 */

declare (strict_types = 1);

/**
 * Implements hook_theme().
 */
function ibm_video_media_type_theme($existing, $type, $theme, $path) {
  return [
    'ibm_video_player' => [
      'variables' => ['videoUrl' => ''],
      'template' => 'ibm_video_player',
    ],
  ];
}
