field.formatter.settings.ibm_video:
  type: mapping
  label: IBM Video Player Configuration
  mapping:
    use_autoplay:
      type: bool
      label: Autoplay
    use_html5_ui:
      type: bool
      label: HTML5 UI
    display_controls:
      type: bool
      label: Display Controls
    initial_volume:
      type: int
      label: Initial Volume
    show_title:
      type: bool
      label: Show Title
    w_mode:
      type: int
      label: WMode
    default_quality:
      type: int
      label: Default Quality
